# Generated by Django 3.0.6 on 2020-06-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionGroups',
        ),
    ]
