# Generated by Django 3.0.6 on 2020-07-04 07:08

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('page', '0002_auto_20200701_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='postquestion',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
