# Generated by Django 3.0.6 on 2020-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20200709_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postquestion',
            name='text_content',
            field=models.CharField(max_length=10000),
        ),
    ]
