# Generated by Django 3.0.6 on 2020-06-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_postanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postanswer',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postanswers', to='page.PostQuestion'),
        ),
    ]
